<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CargaPonderacion extends Model
{
	use SoftDeletes;

	public function __construct(array $attributes = array())
	{
		parent::__construct($attributes);

	}

	//Mass Assignment
	protected $fillable = ['ponderacion_id', 'name', 'porcentaje', 'usu_alta_id', 'usu_mod_id', 'tiene_detalle', 'padre_id', 'bnd_activo'];

	public function usu_alta()
	{
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	} // end

	public function usu_mod()
	{
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	} // end

	public function padre()
	{
		return $this->hasOne('App\CargaPonderacion', 'id', 'padre_id');
	} // end
	public function ponderacion()
	{
		return $this->hasOne('App\Ponderacion', 'id', 'ponderacion_id');
	} // end

	protected $dates = ['deleted_at'];

	// generated by relation command - CargaPonderacion,CalendarioEvaluacion - start
	public function calendarioEvaluacions()
	{
		return $this->hasMany('App\CalendarioEvaluacion');
	} // end
}
