<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Horario extends Model
{
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);

    } 

	//Mass Assignment
	protected $fillable = ['asignacion_academica_id','dia_id','hora','duracion_clase','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Lectivo,Horario - start
	public function lectivo() {
		return $this->belongsTo('App\Lectivo');
	}// end

	public function dia() {
		return $this->belongsTo('App\Dium');
	}// end

	public function asignacionAcademica() {
		return $this->belongsTo('App\AsignacionAcademica');
	}// end

}