<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ReglaRecargo extends Model
{
   
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		
    } 

	//Mass Assignment
	protected $fillable = ['name','dia_inicio','dia_fin','tipo_regla_id','porcentaje', 'monto','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end
        
        public function planPagoLns() {
		return $this->belongsToMany('App\PlanPagoLn');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - TipoRegla,ReglaRecargo - start
	public function tipoRegla() {
		return $this->belongsTo('App\TipoRegla');
	}// end
}